# Generated by Django 4.2.3 on 2023-11-24 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0002_alter_products_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='discreption',
            new_name='description',
        ),
    ]
