# Generated by Django 4.2.3 on 2023-11-24 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0004_products_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='code',
            field=models.CharField(max_length=7, null=True, verbose_name='کد کالا'),
        ),
    ]
