# Generated by Django 4.2.3 on 2023-11-26 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0005_alter_products_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='created',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='تاریخ ایجاد'),
        ),
    ]
