# Generated by Django 4.2.3 on 2023-11-26 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0007_products_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='price_off',
            field=models.IntegerField(null=True, verbose_name='قیمت تخقیف'),
        ),
    ]
