# Generated by Django 4.2.3 on 2023-11-27 04:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0008_products_price_off'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='ratting',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='امتیاز'),
        ),
        migrations.AlterField(
            model_name='products',
            name='slug',
            field=models.SlugField(default='', unique=True),
        ),
    ]
