# Generated by Django 4.2.3 on 2023-11-27 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0011_alter_products_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imageofslider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('short_description', models.CharField(max_length=150, verbose_name='توضیح کوتاه')),
                ('description', models.TextField(verbose_name='توضیح ')),
                ('image', models.ImageField(upload_to='slider')),
            ],
            options={
                'verbose_name': 'عکس اسلایدر',
                'verbose_name_plural': 'اسلایدر',
            },
        ),
    ]
